### ISSUE TITLE
Ola, @caue-alves

### ISSUE THREAD

**Issue by Felipe-Souza-Pereira-Lima** [caue-alves/caue-alves.github.io#2]
A linguagem Jaguar é de baixo ou auto nivel? Na descrição diz que ela é de baixo nivel e no README diz que ela é de alto nivel!

**Comment by caue-alves** [comment]
Kkkk desculpa, me confundi na descrição, acho que eu tava meio cansado e troquei as bolas, ela é de alto nível, pois é mais perto da linguagem humana, vou arrumar pra não confundir mais ninguém

**Comment by caue-alves** [comment]
Arrumado!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
A bom, estou criando um simulador de Linux Ubuntu até agora ele pode instalar pacotes é fazer algumas conexões por IPV4\TCP em Python! E para usuarios Windows que não tem o Python 3 instalado não precisa instalar pois ele esta em .exe e ja vem com Python3 instalado nas entranhas. Estava aqui pensando se você poderia entrar em minha organização tipo depois de eu reinstalar o Windows do netbook pois ele inicia no Modo de Repari Automático e depois quando continua a inicialização ele mostra o erro clássico do Windows a tela azul? Preciso de uma outra linguagem não sendo o shell script, que ele pode interpretar pelo Bash além de usar o NANO 4.0.9. poderia ser a linguagem Jaguar e compilar para Python 3 o que ele intende, aceita?```
https://github.com/Dsa-Terminal
```

**Comment by caue-alves** [comment]
Boa Noite, se quiser eu aceito te ajudar em seu projeto, mas aí você precisa me enviar o convite da organização. Mas bom, Jaguar compila em PHP e ainda está em desenvolvimento, mas posso compilar em Python 3. Caso queira, também programo em C#, que interage muito bem com o Windows. Mas enfim, aceito!

**Comment by caue-alves** [comment]
Poderia me explicar melhor seu simulador? Pois não entendi se é uma VM ou um Terminal Linux em Windows

**Comment by caue-alves** [comment]
(VM é __**Virtual Machine**__)

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Oi bom dia! É um terminal não é uma VM, a quando meu PC voltar do conserto te mando um convite.

**Comment by caue-alves** [comment]
Entendi! Tipo um emulador, ok. Vou te ajudar!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Funcionamento:

Ele só usa um arquivo o Terminal.py e para que não tem o Python3 instalado não é poblema existe o Terminal.exe embora ja venha com o Git e o Python3 instalado nas entranhas. E para não ficar inso em um editor e voltando edle ja vem com o Nano 4.0.9 tudo em /Bin. Usando o git para instalação de pocotes publicados como repositorios no https://github.com/Dsa-Terminal.
Onde o que não é considerado principal é um pacote.

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Por exemplo o Bash que  insterpreta o shell script é principal esta em /Bin/bin
Arquivos temporários em /Bin/Temp e os arquivos do usuario /Bin/Files e o interpretador Python em /Python

**Comment by caue-alves** [comment]
Ok, entendi

**Comment by Felipe-Souza-Pereira-Lima** [comment]
OK.

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Acredita, reinstalei o Windows  e o computador não inicia fica em um loop infinito! Ter que infelizmente mandar para a assistencia tecnica😭! Posso perder tudo!!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Meu email: @caue-alves : salve.laborator12@outlook.com

**Comment by caue-alves** [comment]
Já tive esse problema, ele sempre diz q tem algum problema e quando tu diz pra ele reiniciar mesmo assim ele volta naquele problema @Felipe-Souza-Pereira-Lima.

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Acho ruim concersar no GitHub, não  da para ver se o outro viu a mensagem

**Comment by caue-alves** [comment]
O meu é caue.mendes.rodrigues.alves@gmail.com

**Comment by caue-alves** [comment]
Uma dúvida, que empresa é essa q vc trabalha Dsa Headquarters e que vc coloca o nome em todos os repos, tem alguma coisa a ver com o **D**emocratic **S**ocialists of **A**merica?

**Comment by caue-alves** [comment]
@Felipe-Souza-Pereira-Lima, alguma recomendação para conversar?

**Comment by caue-alves** [comment]
O Hangouts pode ser

**Comment by caue-alves** [comment]
Pra conversar

**Comment by caue-alves** [comment]
Te enviei um convite do Hangouts pelo seu email salve.laborator@gmail.com

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Nada a ver com aquela DSA
Essa significa:
**D**on't  **S**top **A**lthough failture

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Hangustusts esta bom vou instalar

**Comment by caue-alves** [comment]
Ok, desculpa. É que eu pesquisei na internet e eu achei essa. Aí eu pensei que fosse rsrs.

**Comment by caue-alves** [comment]
@Felipe-Souza-Pereira-Lima ok

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Só não me liga! Prefiro as mensagens

**Comment by caue-alves** [comment]
Eu também.

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Usa o email do meu github

**Comment by caue-alves** [comment]
o do seu README?

**Comment by caue-alves** [comment]
Mandei para esse: salve.laborator@gmail.com

**Comment by Felipe-Souza-Pereira-Lima** [comment]
A foto do seu perfil é você aquela cronça ou é seu filho?

**Comment by caue-alves** [comment]
Meu filho

**Comment by Felipe-Souza-Pereira-Lima** [comment]
A menininho bonito

**Comment by caue-alves** [comment]
Meu filho

**Comment by caue-alves** [comment]
@Felipe-Souza-Pereira-Lima kkkkk

**Comment by caue-alves** [comment]
Quer saber cara

**Comment by caue-alves** [comment]
Sou eu mesmo

**Comment by caue-alves** [comment]
kkkk

**Comment by caue-alves** [comment]
Sei que sou meio pequeno dmais pra isso

**Comment by caue-alves** [comment]
mas blz

**Comment by caue-alves** [comment]
Se não quiser mais falar com um piazinho que nem eu tudo bem.

**Comment by caue-alves** [comment]
Eu entendo

**Comment by caue-alves** [comment]
Só tenho 13 anos -_-

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Te enviei um convite em eersc12@gmail.com

**Comment by caue-alves** [comment]
Ok, se vc quer mesmo hehe
